/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 loquat.glb --transform 
Files: loquat.glb [917.78KB] > /Users/corneliusgutsu/Documents/loquatweb/loquat-project/public/loquat-transformed.glb [42.96KB] (95%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/loquat-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.loquatFruit.geometry} material={materials['defaultMat.001']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/loquat-transformed.glb')
